export const REQUEST_LOADING = 'request_loading'
export const REQUEST_ERROR = 'request_error'
export const REQUEST_FAIL = 'request_fail'
export const REQUEST_SUCCESS = 'request_success'
export const GET_ROUTE_SUCCESS = 'get_route_success'
export const RESET_MAP = 'reset_map'
export const INIT_MAP = 'init_map'
