export const REQUEST_LOADING = 'request_loading'
export const REQUEST_ERROR = 'request_error'
export const REQUEST_FAIL = 'request_fail'
export const GET_ROUTE_SUCCESS = 'get_route_success'
export const RESET = 'reset'
